// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EjCascader: typeof import('@ej/ui')['EjCascader']
    EjIcon: typeof import('@ej/ui')['EjIcon']
    EjLayer: typeof import('@ej/ui')['EjLayer']
    EjSearch: typeof import('@ej/ui')['EjSearch']
    EjSearchInput: typeof import('@ej/ui')['EjSearchInput']
    EjSelect: typeof import('@ej/ui')['EjSelect']
    EjTexts: typeof import('@ej/ui')['EjTexts']
    EjTree: typeof import('@ej/ui')['EjTree']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Tree: typeof import('./src/components/base/tree.vue')['default']
  }
}

export { }
