query daQueryMenuList ($menuType: MenuManagementEnum!, $parentId: ID) {
  result: daQueryMenuList (menuType: $menuType, parentId: $parentId) {
    id
    menuName
    parentId
    menuType
    menuManagementType
  }
}
